### ISSUE TITLE
ReferenceError: Property 'Reflect' doesn't exists, js engine: hermes

### ISSUE THREAD

**Issue by Kailash23** [es-shims/Reflect.ownKeys#8]
Hermes unable to find property `Reflect ` even after installing `react.ownkeys` shim.

```
import 'reflect.ownkeys/auto';
import {readFile, DocumentDirectoryPath} from 'react-native-fs';
import pMemoize from 'p-memoize';

const generatePath = partialWord => {
  const basePath = DocumentDirectoryPath + '/WordPowerDB/WordMap';
  return `${basePath}/${partialWord[0]}/${partialWord}-map.json`;
};

export const memGetSuggestions = pMemoize(getSuggestions, {maxAge: 20000});

function getSuggestions(partialWord) {
  return new Promise(async resolve => {
    let path = generatePath(partialWord);
    try {
      let output = await readFile(path);
      console.log('<Heavy call>');
      resolve(JSON.parse(output));
    } catch (e) {
      console.log('Fetching suggestions : ', e);
      resolve([]);
    }
  });
}
```
**[Error](https://word-power-f39ad.web.app/Error.png)**

**Comment by ljharb** [comment]
I see metro being used, and i wonder whether that’s related.

Make sure you’re importing reflect.ownkeys/auto in the *first line of your entire app* - otherwise, any module that’s evaluated first won’t have Reflect available.

**Comment by Kailash23** [comment]
Apologies for the late reply, still getting the same error even after importing `import 'reflect.ownkeys/auto';` on the top of the index.js

**Comment by ljharb** [comment]
What I see in that stack trace is that metro has `src/lib/polyfills/require` - that very much suggests that metro is doing something that breaks polyfilling, such as "loading in a library that depends on polyfillable things, prior to your polyfills having a chance to run". Can you file this issue on metro?

**Comment by Kailash23** [comment]
Okay, @ljharb I am gonna file this issue on the metro. Closing this issue here. Thanks!

**Comment by ljharb** [comment]
Thanks, please link it here when you do; if there's anything actionable for this package I'm happy to reopen and fix it.
